kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: minecraft-operator-go
subjects:
- kind: ServiceAccount
  name: minecraft-operator-go
  namespace: default
roleRef:
  kind: ClusterRole
  name: minecraft-operator-go
  apiGroup: rbac.authorization.k8s.io
